#!/bin/bash

checkFiles=("logger" "include")
numFiles=${#checkFiles[@]}

quitIfFail ( ) 
{
  if [ $? -gt 0 ]
  then
    exit
  fi
}

for (( i=0; i<${numFiles}; i++ ));
do
  echo Running jsLint on ${checkFiles[$i]}.js
  java -jar js/util/shrinksafe/js.jar js/tests/jslint.js js/${checkFiles[$i]}.js
  quitIfFail
done

#unit testing:
#echo Running rhinoTest.js
#java -jar js/util/shrinksafe/js.jar rhinoTest.js 


