#!/bin/bash

checkFiles=(
  "logger" 
  "include"

  "tests/loggerTest"

)
numFiles=${#checkFiles[@]}

quitIfFail ( ) 
{
  if [ $? -gt 0 ]
  then
    exit
  fi
}

for (( i=0; i<${numFiles}; i++ ));
do
  echo Running jsLint on ${checkFiles[$i]}.js
  java -jar js/util/shrinksafe/js.jar js/tests/jslint.js ./js/${checkFiles[$i]}.js
  quitIfFail
done

#unit testing:

tests=(
  "logger"
)
numTests=${#tests[@]}

for (( i=0; i<${numTests}; i++ ));
do
  echo Running test for ${tests[$i]}.js
  java -jar js/util/shrinksafe/js.jar ./js/tests/${tests[$i]}Test.js
  quitIfFail
done


#echo Running rhinoTest.js
#java -jar js/util/shrinksafe/js.jar rhinoTest.js 


