#!/bin/bash

#quit if any command causes an error
set -e

checkFiles=(
  "diom/diom"
  "diom/logger" 
  "diom/include"
  "diom/irc"
  "diom/connection/connection"
  "diom/connection/user"
  "diom/connection/activityItem"
  "diom/connection/activityList"
  "diom/connection/channel"
  "diom/topics"

  "tests/loggerTest"

)
numFiles=${#checkFiles[@]}

for (( i=0; i<${numFiles}; i++ ));
do
  echo Running jsLint on ${checkFiles[$i]}.js
  java -jar js/util/shrinksafe/js.jar js/tests/jslint.js ./js/${checkFiles[$i]}.js
done

#unit testing:

tests=(
  "logger"
)
numTests=${#tests[@]}

for (( i=0; i<${numTests}; i++ ));
do
  echo Running test for ${tests[$i]}.js
  java -jar js/util/shrinksafe/js.jar ./js/tests/${tests[$i]}Test.js
done

echo Finished tests!


