#!/bin/bash

set -e

./checkErrors
./createRelease

jsFiles=(
  "AIRAliases"
  "AIRIntrospector"
  "release/dojo/dojo/dojo.js.uncompressed"
  "release/dojo/diom/diom.js.uncompressed"
)
numFiles=${#jsFiles[@]}

jsFilesAdded=""

for (( i=0; i<${numFiles}; i++ ));
do
  echo appending ./js/${jsFiles[$i]}.js
  jsFilesAdded="${jsFilesAdded} ./js/${jsFiles[$i]}.js"
done

echo js files added: $jsFilesAdded

cert="-package -storetype pkcs12 -keystore apphacker.pfx"
binaryName="DiomedesPreview.air"
htmlFiles="indexDebug.html"
resourceDirs="icons/ css/ images/"
configFile="Diomedes-app-alpha.xml"
otherResources="usa.zwl"
xmlFiles="updateConfig.xml preferences.xml"
swfFiles="servicemonitor.swf applicationupdater_ui.swf spellingENgine.swf"

configVars="${cert} ${binaryName} ${configFile} ${xmlFiles} ${htmlFiles} ${swfFiles} ${otherResources} ${jsFilesAdded} ${resourceDirs} LICENSE"
echo ~/air/bin/adt $configVars

~/air/bin/adt $configVars
echo Created $binaryName release

